import json
from copy import deepcopy

import psycopg
from psycopg.rows import dict_row


def init_db(database_url: str) -> None:
    statements = [
        """
        CREATE TABLE IF NOT EXISTS keywords (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            keyword TEXT NOT NULL,
            created_at TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS raw_leads (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            keyword TEXT NOT NULL,
            sector TEXT NOT NULL,
            company_name TEXT NOT NULL,
            website TEXT NOT NULL,
            source TEXT NOT NULL,
            status TEXT NOT NULL,
            research_status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT,
            reviewed_at TEXT,
            review_note TEXT,
            company_summary TEXT,
            recent_signal TEXT,
            fit_reason TEXT,
            summary TEXT,
            priority TEXT,
            confidence TEXT,
            data_reliability TEXT,
            decision_maker_json TEXT,
            missing_fields_json TEXT,
            personal_notes_json TEXT,
            research_bundle_json TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS leads (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            raw_lead_id INTEGER NOT NULL REFERENCES raw_leads(id),
            company_name TEXT NOT NULL,
            keyword TEXT NOT NULL,
            sector TEXT NOT NULL,
            website TEXT NOT NULL,
            status TEXT NOT NULL,
            crm_status TEXT NOT NULL,
            outreach_status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            sales_owner TEXT,
            company_summary TEXT,
            recent_signal TEXT,
            fit_reason TEXT,
            summary TEXT,
            priority TEXT,
            confidence TEXT,
            data_reliability TEXT,
            decision_maker_json TEXT,
            missing_fields_json TEXT,
            first_message_json TEXT,
            follow_up_message_json TEXT,
            activity_log_json TEXT,
            crm_record_json TEXT,
            last_reply_json TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS ai_drafts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type TEXT NOT NULL,
            entity_id INTEGER NOT NULL,
            draft_type TEXT NOT NULL,
            provider TEXT NOT NULL,
            status TEXT NOT NULL,
            actor_name TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT,
            approved_at TEXT,
            approved_by TEXT,
            request_payload_json TEXT NOT NULL,
            response_payload_json TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS research_runs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            raw_lead_id INTEGER NOT NULL REFERENCES raw_leads(id),
            actor_name TEXT NOT NULL,
            mode TEXT NOT NULL,
            status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            completed_at TEXT,
            request_payload_json TEXT NOT NULL,
            result_payload_json TEXT,
            error_message TEXT
        )
        """,
    ]

    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            for statement in statements:
                cursor.execute(statement)
            cursor.execute(
                "ALTER TABLE raw_leads ADD COLUMN IF NOT EXISTS research_bundle_json TEXT"
            )


def get_connection(database_url: str):
    return psycopg.connect(database_url, row_factory=dict_row)


def healthcheck(database_url: str) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1 AS ok")
            row = cursor.fetchone()

    return {
        "ok": bool(row["ok"]),
        "backend": "postgres",
    }


def create_keyword(database_url: str, keyword: str, created_at: str) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO keywords (keyword, created_at)
                VALUES (%s, %s)
                RETURNING id, keyword, created_at
                """,
                (keyword, created_at),
            )
            row = cursor.fetchone()

    return row


def list_keywords(database_url: str) -> list[dict]:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT id, keyword, created_at
                FROM keywords
                ORDER BY id DESC
                """
            )
            return cursor.fetchall()


def next_raw_lead_id(database_url: str) -> int:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT COALESCE(MAX(id), 0) + 1 AS next_id FROM raw_leads")
            row = cursor.fetchone()

    return int(row["next_id"])


def create_raw_lead(database_url: str, record: dict) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO raw_leads (
                    keyword,
                    sector,
                    company_name,
                    website,
                    source,
                    status,
                    research_status,
                    created_at,
                    updated_at,
                    reviewed_at,
                    review_note,
                    company_summary,
                    recent_signal,
                    fit_reason,
                    summary,
                    priority,
                    confidence,
                    data_reliability,
                    decision_maker_json,
                    missing_fields_json,
                    personal_notes_json,
                    research_bundle_json
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING *
                """,
                _raw_lead_values(record),
            )
            row = cursor.fetchone()

    return _raw_lead_from_row(row)


def list_raw_leads(database_url: str, status: str | None = None) -> list[dict]:
    query = "SELECT * FROM raw_leads"
    params: tuple = ()

    if status:
        query += " WHERE status = %s"
        params = (status,)

    query += " ORDER BY id DESC"

    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(query, params)
            rows = cursor.fetchall()

    return [_raw_lead_from_row(row) for row in rows]


def get_raw_lead(database_url: str, raw_lead_id: int) -> dict | None:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM raw_leads WHERE id = %s", (raw_lead_id,))
            row = cursor.fetchone()

    if not row:
        return None

    return _raw_lead_from_row(row)


def save_raw_lead(database_url: str, record: dict) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE raw_leads
                SET keyword = %s,
                    sector = %s,
                    company_name = %s,
                    website = %s,
                    source = %s,
                    status = %s,
                    research_status = %s,
                    created_at = %s,
                    updated_at = %s,
                    reviewed_at = %s,
                    review_note = %s,
                    company_summary = %s,
                    recent_signal = %s,
                    fit_reason = %s,
                    summary = %s,
                    priority = %s,
                    confidence = %s,
                    data_reliability = %s,
                    decision_maker_json = %s,
                    missing_fields_json = %s,
                    personal_notes_json = %s,
                    research_bundle_json = %s
                WHERE id = %s
                RETURNING *
                """,
                _raw_lead_values(record) + (record["id"],),
            )
            row = cursor.fetchone()

    return _raw_lead_from_row(row)


def create_research_run(database_url: str, record: dict) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO research_runs (
                    raw_lead_id,
                    actor_name,
                    mode,
                    status,
                    created_at,
                    completed_at,
                    request_payload_json,
                    result_payload_json,
                    error_message
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING *
                """,
                _research_run_values(record),
            )
            row = cursor.fetchone()

    return _research_run_from_row(row)


def list_research_runs(database_url: str, raw_lead_id: int | None = None) -> list[dict]:
    query = "SELECT * FROM research_runs"
    params = []

    if raw_lead_id is not None:
        query += " WHERE raw_lead_id = %s"
        params.append(raw_lead_id)

    query += " ORDER BY id DESC"

    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(query, tuple(params))
            rows = cursor.fetchall()

    return [_research_run_from_row(row) for row in rows]


def create_lead(database_url: str, record: dict) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO leads (
                    raw_lead_id,
                    company_name,
                    keyword,
                    sector,
                    website,
                    status,
                    crm_status,
                    outreach_status,
                    created_at,
                    sales_owner,
                    company_summary,
                    recent_signal,
                    fit_reason,
                    summary,
                    priority,
                    confidence,
                    data_reliability,
                    decision_maker_json,
                    missing_fields_json,
                    first_message_json,
                    follow_up_message_json,
                    activity_log_json,
                    crm_record_json,
                    last_reply_json
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING *
                """,
                _lead_values(record),
            )
            row = cursor.fetchone()

    return _lead_from_row(row)


def list_leads(database_url: str, status: str | None = None) -> list[dict]:
    query = "SELECT * FROM leads"
    params: tuple = ()

    if status:
        query += " WHERE status = %s"
        params = (status,)

    query += " ORDER BY id DESC"

    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(query, params)
            rows = cursor.fetchall()

    return [_lead_from_row(row) for row in rows]


def get_lead(database_url: str, lead_id: int) -> dict | None:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM leads WHERE id = %s", (lead_id,))
            row = cursor.fetchone()

    if not row:
        return None

    return _lead_from_row(row)


def save_lead(database_url: str, record: dict) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE leads
                SET raw_lead_id = %s,
                    company_name = %s,
                    keyword = %s,
                    sector = %s,
                    website = %s,
                    status = %s,
                    crm_status = %s,
                    outreach_status = %s,
                    created_at = %s,
                    sales_owner = %s,
                    company_summary = %s,
                    recent_signal = %s,
                    fit_reason = %s,
                    summary = %s,
                    priority = %s,
                    confidence = %s,
                    data_reliability = %s,
                    decision_maker_json = %s,
                    missing_fields_json = %s,
                    first_message_json = %s,
                    follow_up_message_json = %s,
                    activity_log_json = %s,
                    crm_record_json = %s,
                    last_reply_json = %s
                WHERE id = %s
                RETURNING *
                """,
                _lead_values(record) + (record["id"],),
            )
            row = cursor.fetchone()

    return _lead_from_row(row)


def create_ai_draft(database_url: str, record: dict) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                INSERT INTO ai_drafts (
                    entity_type,
                    entity_id,
                    draft_type,
                    provider,
                    status,
                    actor_name,
                    created_at,
                    updated_at,
                    approved_at,
                    approved_by,
                    request_payload_json,
                    response_payload_json
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                RETURNING *
                """,
                _ai_draft_values(record),
            )
            row = cursor.fetchone()

    return _ai_draft_from_row(row)


def list_ai_drafts(
    database_url: str,
    entity_type: str | None = None,
    entity_id: int | None = None,
    draft_type: str | None = None,
    status: str | None = None,
) -> list[dict]:
    query = "SELECT * FROM ai_drafts"
    clauses = []
    params = []

    if entity_type:
        clauses.append("entity_type = %s")
        params.append(entity_type)
    if entity_id is not None:
        clauses.append("entity_id = %s")
        params.append(entity_id)
    if draft_type:
        clauses.append("draft_type = %s")
        params.append(draft_type)
    if status:
        clauses.append("status = %s")
        params.append(status)

    if clauses:
        query += " WHERE " + " AND ".join(clauses)

    query += " ORDER BY id DESC"

    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(query, tuple(params))
            rows = cursor.fetchall()

    return [_ai_draft_from_row(row) for row in rows]


def get_ai_draft(database_url: str, draft_id: int) -> dict | None:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM ai_drafts WHERE id = %s", (draft_id,))
            row = cursor.fetchone()

    if not row:
        return None

    return _ai_draft_from_row(row)


def save_ai_draft(database_url: str, record: dict) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE ai_drafts
                SET entity_type = %s,
                    entity_id = %s,
                    draft_type = %s,
                    provider = %s,
                    status = %s,
                    actor_name = %s,
                    created_at = %s,
                    updated_at = %s,
                    approved_at = %s,
                    approved_by = %s,
                    request_payload_json = %s,
                    response_payload_json = %s
                WHERE id = %s
                RETURNING *
                """,
                _ai_draft_values(record) + (record["id"],),
            )
            row = cursor.fetchone()

    return _ai_draft_from_row(row)


def get_pipeline_summary(database_url: str) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) AS total FROM keywords")
            keyword_total = cursor.fetchone()["total"]
            cursor.execute("SELECT COUNT(*) AS total FROM raw_leads")
            raw_lead_total = cursor.fetchone()["total"]
            cursor.execute("SELECT COUNT(*) AS total FROM leads")
            approved_leads_total = cursor.fetchone()["total"]

    return {
        "keywords_total": int(keyword_total),
        "raw_leads_total": int(raw_lead_total),
        "approved_leads_total": int(approved_leads_total),
        "raw_lead_status": _counter_from_query(database_url, "raw_leads", "status"),
        "lead_status": _counter_from_query(database_url, "leads", "status"),
        "outreach_status": _counter_from_query(database_url, "leads", "outreach_status"),
        "crm_status": _counter_from_query(database_url, "leads", "crm_status"),
    }


def _raw_lead_values(record: dict) -> tuple:
    return (
        record["keyword"],
        record["sector"],
        record["company_name"],
        record["website"],
        record["source"],
        record["status"],
        record["research_status"],
        record["created_at"],
        record.get("updated_at"),
        record.get("reviewed_at"),
        record.get("review_note"),
        record.get("company_summary"),
        record.get("recent_signal"),
        record.get("fit_reason"),
        record.get("summary"),
        record.get("priority"),
        record.get("confidence"),
        record.get("data_reliability"),
        _json_dumps(record.get("decision_maker")),
        _json_dumps(record.get("missing_fields", [])),
        _json_dumps(record.get("personal_notes", [])),
        _json_dumps(record.get("research_bundle")),
    )


def _lead_values(record: dict) -> tuple:
    return (
        record["raw_lead_id"],
        record["company_name"],
        record["keyword"],
        record["sector"],
        record["website"],
        record["status"],
        record["crm_status"],
        record["outreach_status"],
        record["created_at"],
        record.get("sales_owner"),
        record.get("company_summary"),
        record.get("recent_signal"),
        record.get("fit_reason"),
        record.get("summary"),
        record.get("priority"),
        record.get("confidence"),
        record.get("data_reliability"),
        _json_dumps(record.get("decision_maker")),
        _json_dumps(record.get("missing_fields", [])),
        _json_dumps(record.get("first_message")),
        _json_dumps(record.get("follow_up_message")),
        _json_dumps(record.get("activity_log", [])),
        _json_dumps(record.get("crm_record")),
        _json_dumps(record.get("last_reply")),
    )


def _ai_draft_values(record: dict) -> tuple:
    return (
        record["entity_type"],
        record["entity_id"],
        record["draft_type"],
        record["provider"],
        record["status"],
        record["actor_name"],
        record["created_at"],
        record.get("updated_at"),
        record.get("approved_at"),
        record.get("approved_by"),
        _json_dumps(record.get("request_payload", {})),
        _json_dumps(record.get("response_payload", {})),
    )


def _research_run_values(record: dict) -> tuple:
    return (
        record["raw_lead_id"],
        record["actor_name"],
        record["mode"],
        record["status"],
        record["created_at"],
        record.get("completed_at"),
        _json_dumps(record.get("request_payload", {})),
        _json_dumps(record.get("result_payload")),
        record.get("error_message"),
    )


def _raw_lead_from_row(row: dict) -> dict:
    return {
        "id": row["id"],
        "keyword": row["keyword"],
        "sector": row["sector"],
        "company_name": row["company_name"],
        "website": row["website"],
        "source": row["source"],
        "status": row["status"],
        "research_status": row["research_status"],
        "created_at": row["created_at"],
        "updated_at": row["updated_at"],
        "reviewed_at": row["reviewed_at"],
        "review_note": row["review_note"],
        "company_summary": row["company_summary"],
        "recent_signal": row["recent_signal"],
        "fit_reason": row["fit_reason"],
        "summary": row["summary"],
        "priority": row["priority"],
        "confidence": row["confidence"],
        "data_reliability": row["data_reliability"],
        "decision_maker": _json_loads(row["decision_maker_json"], {}),
        "missing_fields": _json_loads(row["missing_fields_json"], []),
        "personal_notes": _json_loads(row["personal_notes_json"], []),
        "research_bundle": _json_loads(row["research_bundle_json"], None),
    }


def _lead_from_row(row: dict) -> dict:
    return {
        "id": row["id"],
        "raw_lead_id": row["raw_lead_id"],
        "company_name": row["company_name"],
        "keyword": row["keyword"],
        "sector": row["sector"],
        "website": row["website"],
        "status": row["status"],
        "crm_status": row["crm_status"],
        "outreach_status": row["outreach_status"],
        "created_at": row["created_at"],
        "sales_owner": row["sales_owner"],
        "company_summary": row["company_summary"],
        "recent_signal": row["recent_signal"],
        "fit_reason": row["fit_reason"],
        "summary": row["summary"],
        "priority": row["priority"],
        "confidence": row["confidence"],
        "data_reliability": row["data_reliability"],
        "decision_maker": _json_loads(row["decision_maker_json"], {}),
        "missing_fields": _json_loads(row["missing_fields_json"], []),
        "first_message": _json_loads(row["first_message_json"], None),
        "follow_up_message": _json_loads(row["follow_up_message_json"], None),
        "activity_log": _json_loads(row["activity_log_json"], []),
        "crm_record": _json_loads(row["crm_record_json"], None),
        "last_reply": _json_loads(row["last_reply_json"], None),
    }


def _ai_draft_from_row(row: dict) -> dict:
    return {
        "id": row["id"],
        "entity_type": row["entity_type"],
        "entity_id": row["entity_id"],
        "draft_type": row["draft_type"],
        "provider": row["provider"],
        "status": row["status"],
        "actor_name": row["actor_name"],
        "created_at": row["created_at"],
        "updated_at": row["updated_at"],
        "approved_at": row["approved_at"],
        "approved_by": row["approved_by"],
        "request_payload": _json_loads(row["request_payload_json"], {}),
        "response_payload": _json_loads(row["response_payload_json"], {}),
    }


def _research_run_from_row(row: dict) -> dict:
    return {
        "id": row["id"],
        "raw_lead_id": row["raw_lead_id"],
        "actor_name": row["actor_name"],
        "mode": row["mode"],
        "status": row["status"],
        "created_at": row["created_at"],
        "completed_at": row["completed_at"],
        "request_payload": _json_loads(row["request_payload_json"], {}),
        "result_payload": _json_loads(row["result_payload_json"], None),
        "error_message": row["error_message"],
    }


def _counter_from_query(database_url: str, table_name: str, column_name: str) -> dict:
    with get_connection(database_url) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                f"""
                SELECT {column_name} AS label, COUNT(*) AS total
                FROM {table_name}
                GROUP BY {column_name}
                ORDER BY {column_name}
                """
            )
            rows = cursor.fetchall()

    return {
        row["label"]: row["total"]
        for row in rows
        if row["label"] is not None
    }


def _json_dumps(value):
    if value is None:
        return None

    return json.dumps(value)


def _json_loads(value, fallback):
    if value is None:
        return deepcopy(fallback)

    return json.loads(value)
